App/ookarchyves/models.py
from .. import db
from datetime import datetime

class Themes(db.Model):

    __tablename__ = 'ookarchyves_themes'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    theme_title = db.Column(
        db.String(50),
        nullable=False,

    )
    theme_description = db.Column(
        db.Text,
        nullable=False

    )
    theme_private = db.Column(
        db.Integer,
        default=1,
        nullable=False
    )

    def __repr__(self):
        return '{}'.format(self.theme_title)


class Articles(db.Model):
    __tablename__ = 'ookarchyves_articles'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    article_title = db.Column(
        db.String(100),
        nullable=False,
    )
    article_author_id = db.Column(
        db.Integer
    )
    article_create_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow()
    )
    article_update_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow()
    )
    article_body = db.Column(
        db.Text,
        nullable=False
    )
    article_theme_id = db.Column(
        db.Integer
    )
   
    article_private = db.Column(
        db.Integer,
        default=1,
        nullable=False
    )
    
    def __repr__(self):
        return '<Article {}>'.format(self.article_title)

    def articles_by_theme(self, t_id):
        pass

    

App/ookarchyves/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, StringField, SubmitField, RadioField, SelectField, HiddenField
from wtforms.validators import DataRequired


class ThemeForm(FlaskForm):
    theme_title = StringField(
        'Thèmatique',
        [DataRequired()]
    )
    theme_description = TextAreaField(
        'Description'
    )
    theme_private = RadioField(
        'Visibilité',
        choices=[('0', 'Publique'), ('1', 'Privée')]
    )

    submit = SubmitField('Submit')


class ArticleForm(FlaskForm):
    article_title = StringField(
        'Titre de l\'article : ',
        [DataRequired()]
    )
    article_author_id = HiddenField(
        "user_id"
    )
    article_body = TextAreaField(
        'Article',
        [DataRequired()]
    )
    article_theme_id = SelectField(
        'Categorie existante',
        [DataRequired()]
    )
    article_private = RadioField(
        'Visibilité',
        [DataRequired()],
        choices=[('0', 'Tout le monde'), ('1', 'Privée')]
    )
    submit = SubmitField('Submit')

App/ookarchyves/main.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

# from moc.db import get_db

bp = Blueprint('ookarchyves', __name__, url_prefix='/ookarchyves')

@bp.route('/')
def main():
    module_name = 'Ookarchyves'
    return render_template('module/ookarchyves/main.html', name="Ookamy", menu_active=module_name)

App/ookarchyves/routes.py
from flask import current_app as app
from flask_login import current_user, login_required
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for, jsonify
)
from .. import login_manager
from .models import db, Themes, Articles
from .forms import ThemeForm, ArticleForm

oa_bp = Blueprint(
    'ookarchyves', __name__,
    url_prefix='/ookarchyves',
    template_folder='templates',
    static_folder='static'
)

NAME_MENU = 'Ookarchyves'


@oa_bp.route('/')
@login_required
def oa_index():

    c_theme = Themes.query.count()
    c_article = Articles.query.count()
    themes = Themes.query.all()
    articles = Articles.query.all()

    # Init une list pour y inserer les dict des themes
    menu = []

    # crée l'object theme avec les articles
    for theme in themes:
        t = {}
        t['id'] = theme.id
        t['nom'] = theme.theme_title
        t['description'] = theme.theme_description

        # va chercher les articles correspondants
        arts = Articles.query.filter(
            Articles.article_theme_id == theme.id).all()
        t['articles'] = arts
        menu.append(t)

    return render_template(
        'oa_i.html',
        menu_active=NAME_MENU,
        themes=menu,
        c_theme=Themes.query.count(),
        c_article=Articles.query.count()
    )


@oa_bp.route('/thematique', methods=['GET', 'POST'])
@login_required
def oa_theme():
    form = ThemeForm()
    if form.validate_on_submit():
        existing_theme = Themes.query.filter_by(
            theme_title=form.theme_title.data).first()
        if existing_theme is None:
            theme = Themes(
                theme_title=form.theme_title.data,
                theme_description=form.theme_description.data,
                theme_private=form.theme_private.data,
            )
            db.session.add(theme)
            db.session.commit()  # Create new theme
            return redirect(url_for('ookarchyves.oa_index'))
        flash('Ce theme existe déjà')
    return render_template(
        'oa_theme_form.jinja2',
        menu_active=NAME_MENU,
        form=form
    )


@oa_bp.route('/article', methods=['GET', 'POST'])
@login_required
def oa_article():
    form = ArticleForm()
    # Pour remplir le selectfield \o/ avec la liste de thème
    form.article_theme_id.choices = [
        (t.id, t.theme_title) for t in Themes.query.order_by('theme_title')]
    if form.validate_on_submit():
        existing_theme = Articles.query.filter_by(
            article_title=form.article_title.data).first()
        if existing_theme is None:
            article = Articles(
                article_title=form.article_title.data,
                article_author_id=current_user.id,
                article_body=form.article_body.data,
                article_theme_id=form.article_theme_id.data,
                article_private=form.article_private.data,
            )
            db.session.add(article)
            db.session.commit()  # Create new article
            return redirect(url_for('ookarchyves.oa_index'))
        flash('Cette article existe déjà')
    return render_template(
        'oa_article_form.jinja2',
        menu_active=NAME_MENU,
        form=form
    )

# Read with ajax method


@oa_bp.route('/article-view/')
@login_required
def oa_article_by_id():
    art_id = request.args.get('id')
    if art_id:
        art_request = Articles.query.filter(Articles.id == art_id).all()
        for ar in art_request:
            a = {}
            a['id'] = ar.id
            a['title'] = ar.article_title
            a['create_at'] = ar.article_create_at
            a['update_at'] = ar.article_update_at
            a['body'] = ar.article_body
            a['theme_id'] = ar.article_theme_id
            a['private'] = ar.article_private

    return jsonify(
        response=art_id,
        art_obj=a
    )


# Update de l'article
@oa_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def oa_up(id):
    a = Articles.query.get_or_404(id)
    form = ArticleForm(obj=a)
    form.article_theme_id.choices = [
        (t.id, t.theme_title) for t in Themes.query.order_by('theme_title')]

    if form.validate_on_submit():
        a.article_title = form.article_title.data
        a.article_body = form.article_body.data
        a.article_theme_id = form.article_theme_id.data
        a.article_private = form.article_private.data
        db.session.commit()
        return redirect(url_for('ookarchyves.oa_index'))

    # init form with data
    form.article_title.data = a.article_title
    form.article_body.data = a.article_body
    form.article_theme_id.default = a.article_theme_id
    form.article_private.default = a.article_private

    return render_template(
        'oa_edit_article_form.jinja2',
        menu_active=NAME_MENU,
        form=form
    )


# Delete aricle with ajax method /!\ without agree alerte
@oa_bp.route('/article-d/')
@login_required
def oa_d():
    art_id = request.args.get('id')
    a = Articles.query.get_or_404(art_id)
    if a:
        try:
            db.session.delete(a)
            db.session.commit()
            return jsonify(
                response='D'
            )
        except:
            return jsonify(
                response="l'article n'a pu etre delete"
            )

App/ookarchyves/templates/index.html
{% extends 'base.html' %}

{% block title %}Main,Ookaarchyves{% endblock %}

{% block body %}
je suis le main d'ookarchyves
{% endblock %}

App/ookarchyves/templates/oa_article_form.jinja2
{% extends "base.html" %}

{% block title %} Ajouter un Article{% endblock %}
{% block stylesheet %}
<style>
 form{
     width: 100%;
     background-color: blueviolet;
 }
</style>
{% endblock %}

{% block body %}

{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    {{ message }}
</div>
{% endfor %}

<div class="row" >
<form method="POST" action="article">
    {{ form.csrf_token }}   
    {{ form.article_author_id}}    

    <div class="col s12 m6">
        
        {# Titre de l'article #}
        <fieldset class="name">
            {{ form.article_title.label }}
            {{ form.article_title(placeholder='Sql, Développement, VScode') }}
            {% if form.article_title.errors %}
            <ul class="errors">
            {% for error in form.article_title.errors %}
            <li>{{ error }}</li>{% endfor %}
            </ul>
            {% endif %}
        </fieldset>
        <div class="row">
            <div class="col s6">
                <fieldset class="row theme">
                    <div class="col">{{ form.article_theme_id.label }}</div>
                    <div class="col">{{ form.article_theme_id }}</div>              
                </fieldset>
            </div>
            
            <div class="col s6">
                <div class="row">
                    <div class="col">{{form.article_private.label}} :</div>
                    {% for s in form.article_private %}
                    <div class="col">
                        <p>
                            {{ s(class="with-gap") }}
                            <span>{{ s.label }}</span>
                        </p>
                    </div>
                        {% endfor %}
                    </div>
            </div>
        </div>

        {# Bouton pour tout valider #}
        <div class="submit-button" style="margin-top:10px;">
            {{ form.submit(class="button is-success") }}
        </div>
    </div>

    {# Partie de droite pour le body de l'article #}
    <div class="col s12 m6">
        <fieldset class="description">
            {{ form.article_body.label }}
            {{ form.article_body(class="textarea ", rows="20" ) }}
        </fieldset>
    </div>
</form>
</div>   

{% endblock %}
{% block js %}
<script src="{{url_for('ookarchyves.static', filename='oa.js')}}"></script>
{% endblock %}

App/ookarchyves/templates/oa_edit_article_form.jinja2
{% extends "base.html" %}

{% block title %} Editer l'Article{% endblock %}
{% block stylesheet %}

{% endblock %}

{% block body %}

{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
   {{ message }}
</div>
{% endfor %}

<div class="row">
   <form method="POST" action="">
      {{ form.csrf_token }}
      {{ form.article_author_id}}

      <div class="col s12 m6">

         {# Titre de l'article #}
         <fieldset class="name">
            {{ form.article_title.label }}
            {{ form.article_title(placeholder='Sql, Développement, VScode') }}
            {% if form.article_title.errors %}
            <ul class="errors">
               {% for error in form.article_title.errors %}
               <li>{{ error }}</li>{% endfor %}
            </ul>
            {% endif %}
         </fieldset>
         <div class="row">
            <div class="col s6">
               <fieldset class="row theme">
                  <div class="col">{{ form.article_theme_id.label }}</div>
                  <div class="col">{{ form.article_theme_id }}</div>
               </fieldset>
            </div>

            <div class="col s6">
               <div class="row">
                  <div class="col">{{form.article_private.label}} :</div>
                  {% for s in form.article_private %}
                  <div class="col">
                     <p>
                        {{ s(class="with-gap") }}
                        <span>{{ s.label }}</span>
                     </p>
                  </div>
                  {% endfor %}
               </div>
            </div>
         </div>

         {# Bouton pour tout valider #}
         <div class="submit-button" style="margin-top:10px;">
            {{ form.submit(class="button is-success") }}
         </div>
      </div>

      {# Partie de droite pour le body de l'article #}
      <div class="col s12 m6">
         <fieldset class="description">
            {{ form.article_body.label }}
            {{ form.article_body(class="textarea ", rows="20" ) }}
         </fieldset>
      </div>
   </form>
</div>

{% endblock %}
{% block js %}
<script src="{{url_for('ookarchyves.static', filename='oa.js')}}"></script>
{% endblock %}

App/ookarchyves/templates/oa_i.html
{% extends 'base.html' %}

{% block title %}Main,Ookaarchyves{% endblock %}
{% block topbar %}
<header id="top-bar" class="row">
   <div class="col s4">
      <input class="" type="text" placeholder="Futur cadre de recherche">
   </div>


   <div class="fixed-action-btn">
      <a class="btn-floating btn">
         <i id="ooka-color" class="fas fa-plus"></i>
      </a>
      <ul>
         <li><a class="btn-floating red" title="Ajouter une category" href="{{url_for('ookarchyves.oa_theme')}}">
               <i class="fas fa-folder-plus"></i>
            </a></li>
         <li><a class="btn-floating yellow darken-1" title="Ecrire un article"
               href="{{url_for('ookarchyves.oa_article')}}">
               <i class="fas fa-file-alt"></i>
            </a></li>
      </ul>
   </div>
</header>
{% endblock %}


{% block body %}
<div id="ookarchyves-body" class="row">
   {% for theme in themes %}
   <div class="card col s12">
      <h5>{{theme.nom}}</h5>

      <p> {{theme.description}}</p>
      <div class="card-content">
         {% for art in theme.articles %}
         <button class="oa_article modal-trigger waves-effect waves-light" data-target="article"
            data-article="{{art.id}}" data-url="{{url_for('ookarchyves.oa_article_by_id')}}">
            {{art.article_title}}
         </button>
         {% endfor %}
      </div>
   </div>
   {% endfor %}
</div>


<!-- Modal Structure -->
<div id="article" class="modal modal-fixed-footer">
   <div class="modal-content">
      <h4 id="article-title">article.title</h4>
      <p id="article-body">article.body</p>
   </div>
   <div class="modal-footer">
      <a id="article-edit" class="btn-small green waves-effect waves-light" href=""><i
            class="material-icons">mode_edit</i>
      </a>
      <button id="article-trash" class="btn-small red waves-effect waves-light"
         data-url="{{url_for('ookarchyves.oa_d')}}"><i class="material-icons">delete_forever</i>
      </button>
   </div>
</div>

{% endblock %}

{% block js %}
<script src="{{url_for('ookarchyves.static', filename='oa.js')}}"></script>
{% endblock %}

App/ookarchyves/templates/oa_theme_form.jinja2
{% extends "base.html" %}

{% block title %} Ajouter une Thèmatique{% endblock %}
{% block body %}
  <div class="form-wrapper">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button
          type="button"
          class="close"
          data-dismiss="alert">
          x
        </button>
        {{ message }}
      </div>
    {% endfor %}

    <form method="POST" action="thematique">
    {{ form.csrf_token }}
      <fieldset class="name">
        {{ form.theme_title.label }}
        {{ form.theme_title(placeholder='Sql, Développement, VScode') }}
        {% if form.theme_title.errors %}
          <ul class="errors">
            {% for error in form.theme_title.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>
       <fieldset class="description">
        {{ form.theme_description.label }}
        {{ form.theme_description(class="textarea is-info", rows="10" ) }}
      </fieldset>
      <div class="row">
        {% for s in form.theme_private %}
        <div class="col s3">
          <p>
              {{ s(class="with-gap") }}
              <span>{{ s.label }}</span>
          </p>
        </div>
        {% endfor %}

      </div>
      


    <div class="submit-button" style="margin-top:10px;">
      {{ form.submit(class="button is-success") }}
    </div>

    </form>

{% endblock %}
{% block js %}
<script src="{{url_for('ookarchyves.static', filename='oa.js')}}"></script>
{% endblock %}