App/ookamanager/models.py
from .. import db
from datetime import datetime

class Projects(db.Model):
    __tablename__ = 'ookamanager_projects'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    project_name = db.Column(
        db.String(50),
        nullable=False,
    )
    project_description = db.Column(
        db.Text,
        nullable=False
    )
    project_user_id = db.Column(
        db.Integer,
        nullable=False
    )
    project_create_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow()
    )
    project_update_at  = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow()
    )
    project_finish_at  = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow()
    )
    project_estimation = db.Column(
        db.String(50),
        nullable=False,
    )
    project_deadline = db.Column(
        db.DateTime,
        nullable=True,
    )

    def __repr__(self):
        return '{}'.format(self.project_name)


class Modules(db.Model):
    __tablename__ = 'ookamanager_modules'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    module_name = db.Column(
        db.String(255),
        nullable=False,
    )
    module_visible = db.Column(
        db.Integer,
        default = 1,
    )
    module_color = db.Column(
        db.String(30),
        nullable=True,
    )


class Steps(db.Model):
    __tablename__ = 'ookamanager_steps'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    step_name = db.Column(
        db.String(255),
        nullable=False,
    )
    step_order = db.Column(
        db.Integer,
        default = 1,
    )
    step_visible = db.Column(
        db.Integer,
        default = 1,
    )
    step_color = db.Column(
        db.String(30),
        nullable=True,
    )


class Status(db.Model):
    __tablename__ = 'ookamanager_status'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    status_name = db.Column(
        db.String(255),
        nullable=False,
    )
    status_order = db.Column(
        db.Integer,
        default = 1,
    )
    status_visible = db.Column(
        db.Integer,
        default = 1,
    )


class Tasks(db.Model):
    __tablename__ = 'ookamanager_tasks'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    task_title  = db.Column(
        db.String(255),
        nullable=False,
    )
    task_body  = db.Column(
        db.Text,
    )
    task_order = db.Column(
        db.Integer,
    ) 
    task_project_id = db.Column(
        db.Integer,
    )
    task_module = db.Column(
        db.Integer,
    )
    task_deadline = db.Column(
        db.String(80),
        nullable=True,
    )
    task_step_id = db.Column(
        db.Integer,
    )
    task_user_id= db.Column(
        db.Integer,
        default = 1,
    )
    task_create_at = db.Column(
        db.DateTime,
        nullable=True,
    )
    task_update_at = db.Column(
        db.DateTime,
        nullable=True,
    )

App/ookamanager/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, StringField, SubmitField, RadioField, SelectField, HiddenField, DateField, IntegerField
from wtforms.validators import DataRequired


class ProjectForm(FlaskForm):
    project_name = StringField(
        'Nom du Projet',
        [DataRequired()]
    )
    project_description = TextAreaField(
        'Description du projet'
    )

    project_estimation = StringField(
        'Estimation de l\'importance'
    )
    project_deadline = DateField(
        'Deadline',
    )
    submit = SubmitField('Submit')


class ModuleForm(FlaskForm):
    module_name = StringField(
        'Nom du Module',
        [DataRequired()]
    )
    module_color = StringField(
       'Couleur Materialize : https://materializecss.com/color.html'
   )
    submit = SubmitField('Submit')


class TaskForm(FlaskForm):
    task_title = StringField(
        'Titre de l\'action',
        [DataRequired()]
    )
    task_body = TextAreaField(
       'description'
    )
    task_order  = SelectField(
        'Thematique'
    )
    task_project_id = IntegerField(
        'projet'
    )
    task_module  = SelectField(
        'Thematique'
    )
    task_deadline = DateField(
        'Deadline',
    )
    task_step_id = IntegerField(
        'projet'
    )
    task_user_id = IntegerField(
        'projet'
    )

    submit = SubmitField('Submit')

App/ookamanager/routes.py
from flask import current_app as app
from flask_login import current_user, login_required
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from .. import login_manager
from .models import db, Projects, Modules, Steps, Status, Tasks
from .forms import ProjectForm, ModuleForm, TaskForm


om_bp = Blueprint('ookamanager', __name__,
    url_prefix= '/ookamanager',
    template_folder= 'templates'
)

NAME_MENU= 'Ookamanager'

@om_bp.route('/')
@login_required
def om_index():
    projects = Projects.query.filter_by(project_user_id=current_user.id).all()
    return render_template('om_i.html', menu_active= NAME_MENU,  projects= projects)


@om_bp.route('/projet', methods=['GET', 'POST'])
@login_required
def om_project():
    form = ProjectForm()
    if form.validate_on_submit():
        existing_theme = Projects.query.filter_by(project_name=form.project_name.data).first()
        if existing_theme is None:
            project = Projects(
                project_name=form.project_name.data,
                project_description=form.project_description.data,
                project_user_id= current_user.id,
                project_estimation= form.project_estimation.data,
                project_deadline= form.project_deadline.data,
            )
            db.session.add(project)
            db.session.commit()  # Create new project
            return redirect(url_for('ookamanager.om_index'))
        flash('Ce projet existe déjà')
    return render_template(
        'om_project_form.jinja2',
        form= form,
        menu_active= NAME_MENU
    )


@om_bp.route('/module', methods=['GET', 'POST'])
@login_required
def om_module():
    form = ModuleForm()
    modules = Modules.query.all()
    if form.validate_on_submit():
        existing_theme = Modules.query.filter_by(module_name=form.module_name.data).first()
        if existing_theme is None:
            m = Modules(
                module_name=form.module_name.data,
                module_color=form.module_color.data,
            )
            db.session.add(m)
            db.session.commit()  # Create new theme
            return redirect(url_for('ookamanager.om_module'))
        flash('Ce module existe déjà')
    return render_template(
        'om_module_form.jinja2',
        menu_active= NAME_MENU,
        form= form,
        modules= modules
    )


@om_bp.route('/dashboard/<dashboard_id>', methods=['GET', 'POST'])
@login_required
def om_dashboard(dashboard_id):
    # on va chercher le projet
    dashboard = Projects.query.filter_by(id=dashboard_id).first()
    # Les colonnes steps
    steps = Steps.query.all()
    
    # Si le projet exist on accede au dashboard
    if dashboard is not None and dashboard.project_user_id == current_user.id:
        return render_template(
            'om_dashboard.html',
            dashboard= dashboard,
            steps= steps,
            menu_active= NAME_MENU
        )
    else:
        # redirection si on entre une numero d'id inconnue
        return redirect(url_for('ookamanager.om_index'))
    

@om_bp.route('/task', methods=['GET', 'POST'])
@login_required
def om_add_todo():
    project_id = request.args.get('dashboard_id')
    modules_liste = Modules.query.all()
    form = TaskForm()

    # Pour remplir le selectfield \o/ avec la liste de thème
    form.task_module.choices = [(m.id, m.module_name) for m in Modules.query.order_by('module_name')]

    if form.validate_on_submit():
        existing_theme = Tasks.query.filter_by(task=form.task_title.data).first()
        if existing_theme is None:
            tasks = Task(
                task_title= form.task_title.data,
                task_body= form.task_body.data,
                task_order= 0,
                task_project_id= project_id,
                task_module= form.task_module.data,
                task_deadline= form.task_deadline.data,
                task_step_id= 1,
                task_user_id= current_user.id,
            )
            db.session.add(task)
            db.session.commit()  # Create new theme
            return redirect(url_for('ookamanager.om_dashboard', dashboard_id=project_id))
        flash(' euh Je sais po')

    return render_template(
        'om_task_form.jinja2',
        form= form,
        p_id= project_id,
        menu_active= NAME_MENU
    )

App/ookamanager/templates/index.html
{% extends 'base.html' %}

{% block title %}Main Ookamanager{% endblock %}

{% block body %}
ilsejghiukzhrgioj zhgjiohz giojhzrogi hzrg
{% endblock %}

App/ookamanager/templates/om_dashboard.html
{% extends 'base.html' %}

{% block title %}{{dashboard.project_name}}{% endblock %}
{% block topbar %}
<header id="top-bar">
   <h5>{{dashboard.project_name}}</h5>
   <div class="fixed-action-btn">
      <a class="btn-floating btn">
        <i id="ooka-color" class="fas fa-plus"></i>
      </a>
      <ul>
        <li><a class="btn-floating red" title="Ajouter une taches" href="{{ url_for('ookamanager.om_add_todo',dashboard_id=dashboard.id)}}">
         <i class="fas fa-thumbtack"></i>
        </a></li>

      </ul>
    </div>
</header>
{% endblock %}
{% block body %}
<!-- Afficher le tableau des projets /!\ projet creer par le compte-->
<div id="ookamanager-dashboard" class="row">
  <div class="card-panel ">
      {{dashboard.project_description}}
    <div class="row" style="margin-bottom: 0; padding-bottom: 0;">
      <blockquote class="col s12 m4">{{dashboard.project_create_at}}</blockquote>
      <blockquote class="col s12 m4">{{dashboard.project_estimation}}</blockquote>
      <blockquote class="col s12 m4">{{dashboard.project_deadline}}</blockquote>
    </div>
  </div>

  {% for s in steps |sort(attribute="step_order") %}
    <div class="step-colonne col s12 m4 ">
      <div class="step-head {{s.step_color}}">

        {{s.step_name|upper}}
      </div>
      <div class="step-body">
        <div class="card-panel ">1</div>
        <div class="card-panel ">2</div>
        <div class="card-panel ">3</div>
        <div class="card-panel ">4</div>
        <div class="card-panel ">5</div>
        <div class="card-panel ">6</div>
      </div>
      
    </div>
  {% endfor %}   

{% endblock %}

App/ookamanager/templates/om_i.html
{% extends 'base.html' %}

{% block title %}Projet de {{current_user}}{% endblock %}
{% block topbar %}
<header id="top-bar">
  <div class="fixed-action-btn">
    <a class="btn-floating btn">
      <i id="ooka-color" class="fas fa-plus"></i>
    </a>
    <ul>
      <li><a class="btn-floating red" title="Ajouter un project" href="{{url_for('ookamanager.om_project')}}">
        <i class="far fa-lightbulb"></i>
      </a></li>
      <li><a class="btn-floating red" title="Ajouter un Module" href="{{url_for('ookamanager.om_module')}}">
        <i class="far fa-bookmark"></i>
      </a></li>
    </ul>
  </div>
</header>
{% endblock %}
{% block body %}
<!-- Afficher le tableau des projets /!\ projet creer par le compte-->
<div id="ookamanager-body" class="row">
  {% for p in projects %}
      <div class="card col s12" >    
              <h5>{{p.project_name}}</h5>
              <p> {{p.project_description}}</p>
              <a href="{{url_for('ookamanager.om_dashboard', dashboard_id=p.id)}}"><i class="fas fa-angle-double-right"></i></a>
             
{{p.id}}
        <div class="card-content">
          Faire le resumer des colonnes des conteurs de tache et compter le nb de jour avant la deatline
        </div>
      </div>
  {% endfor %}
</div>




{% endblock %}

App/ookamanager/templates/om_module_form.jinja2
{% extends "base.html" %}

{% block title %} Ajouter un Module{% endblock %}

{% block body %}
  <div class="form-wrapper">
    <h5>Nouveau Module</h5>
    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button
          type="button"
          class="close"
          data-dismiss="alert">
          x
        </button>
        {{ message }}
      </div>
    {% endfor %}

    <form method="POST" action="module">
    {{ form.csrf_token }}
      <fieldset class="name">
        {{ form.module_name.label }}
        {{ form.module_name(placeholder='Setting') }}
        {% if form.module_name.errors %}
          <ul class="errors">
            {% for error in form.module_name.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>
       <fieldset class="couleur">
        {{ form.module_color.label }}
        {{ form.module_color}}
      </fieldset>
    
        <div class="submit-button" style="margin-top:10px;">
        {{ form.submit(class="button is-success") }}
        </div>
    </form>

    <div>
      <h5>Modules existant</h5>
      <div class="row">
        {% for m in modules %}
          <div class="col s4">
          <div class="card {{m.module_color}}">
            {{m.module_name}} - {{m.module_color}} - visible: {{m.module_visible}}

          </div>

          </div>
          {% endfor %}
      </div>
    </div>
</div>
{% endblock %}

App/ookamanager/templates/om_project_form.jinja2
{% extends "base.html" %}

{% block title %} Ajouter un Projet{% endblock %}

{% block body %}
  <div class="form-wrapper">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button
          type="button"
          class="close"
          data-dismiss="alert">
          x
        </button>
        {{ message }}
      </div>
    {% endfor %}

    <form method="POST" action="projet">
    {{ form.csrf_token }}
      <fieldset class="name">
        {{ form.project_name.label }}
        {{ form.project_name(placeholder='Super Potatoes') }}
        {% if form.project_name.errors %}
          <ul class="errors">
            {% for error in form.project_name.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>
       <fieldset class="description">
        {{ form.project_description.label }}
        {{ form.project_description(class="textarea is-info", rows="4" ) }}
      </fieldset>
         <fieldset class="estimation">
         {{form.project_estimation.label}}
         {{form.project_estimation}}
         </fieldset>
         <fieldset class="deadline">
         {{form.project_deadline.label}}
         {{form.project_deadline(type='date')}}
         </fieldset>

    <div class="submit-button" style="margin-top:10px;">
      {{ form.submit(class="button is-success") }}
    </div>

    </form>

{% endblock %}

App/ookamanager/templates/om_task_form.jinja2
{% extends "base.html" %}

{% block title %} Ajouter une action{% endblock %}

{% block body %}
  <div class="form-wrapper">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button
          type="button"
          class="close"
          data-dismiss="alert">
          x
        </button>
        {{ message }}
      </div>
    {% endfor %}
<div class="row" >
    <form method="POST" action="task">
      {{ form.csrf_token }}
      <div class="col s6 m6">
        <fieldset class="title">
          {{ form.task_title.label }}
          {{ form.task_title }}
        </fieldset>
        <fieldset class="body">
          {{ form.task_body.label }}
          {{ form.task_body(class="textarea ", rows="4" ) }}
        </fieldset>
        <div class="row">
          <div class="col s6">
            <fieldset class="module select">
              {{ form.task_module.label }}
              {{ form.task_module }}
            </fieldset>
          </div>
          <div class="col s6">
            <fieldset class="deadline">
              {{ form.task_deadline.label }}
              {{ form.task_deadline(type='date') }}
            </fieldset>
          </div>
        </div>

        <div class="submit-button" style="margin-top:10px;">
          {{ form.submit(class="button is-success") }}
        </div>
      </div>
    </form>
  </div>

{% endblock %}